//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMigration.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBMigration.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding outsourcer by name: {0}.
        /// </summary>
        internal static string AddingOutsourcerByNameTemplate {
            get {
                return ResourceManager.GetString("AddingOutsourcerByNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleted {0} record(s) from addendum.
        /// </summary>
        internal static string DeletedRecordsForAddendumTemplate {
            get {
                return ResourceManager.GetString("DeletedRecordsForAddendumTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleted {0} record(s) from invoces.
        /// </summary>
        internal static string DeletedRecordsForInvocesTemplate {
            get {
                return ResourceManager.GetString("DeletedRecordsForInvocesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleted {0} record(s) from contractors.
        /// </summary>
        internal static string DeletedRecordsFromContractorsTemplate {
            get {
                return ResourceManager.GetString("DeletedRecordsFromContractorsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleted {0} record(s) from contracts.
        /// </summary>
        internal static string DeletedRecordsFromContractsTemplate {
            get {
                return ResourceManager.GetString("DeletedRecordsFromContractsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleted {0} record(s) from customerContracts.
        /// </summary>
        internal static string DeletedRecordsFromCustomerContractsTemplate {
            get {
                return ResourceManager.GetString("DeletedRecordsFromCustomerContractsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleted {0} record(s) from customers.
        /// </summary>
        internal static string DeletedRecordsFromCustomersTemplate {
            get {
                return ResourceManager.GetString("DeletedRecordsFromCustomersTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleted {0} record(s) from employees.
        /// </summary>
        internal static string DeletedRecordsFromEmployeesTemplate {
            get {
                return ResourceManager.GetString("DeletedRecordsFromEmployeesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found contract for outsourcer: {0}.
        /// </summary>
        internal static string FoundContractForOutsourcer {
            get {
                return ResourceManager.GetString("FoundContractForOutsourcer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found invoce for customer: {0}.
        /// </summary>
        internal static string FoundInvoceForCustomerTemplate {
            get {
                return ResourceManager.GetString("FoundInvoceForCustomerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found outsourcer by name: {0}.
        /// </summary>
        internal static string FoundOutsourcerByNameTemplate {
            get {
                return ResourceManager.GetString("FoundOutsourcerByNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context.
        /// </summary>
        internal static string NodeContext {
            get {
                return ResourceManager.GetString("NodeContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docs.
        /// </summary>
        internal static string NodeDocument {
            get {
                return ResourceManager.GetString("NodeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        internal static string NodeEmployees {
            get {
                return ResourceManager.GetString("NodeEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на References.
        /// </summary>
        internal static string NodeReferences {
            get {
                return ResourceManager.GetString("NodeReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stand.
        /// </summary>
        internal static string NodeStand {
            get {
                return ResourceManager.GetString("NodeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press any key to continue.
        /// </summary>
        internal static string PressAnyKeyMessage {
            get {
                return ResourceManager.GetString("PressAnyKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stand.
        /// </summary>
        internal static string StringStand {
            get {
                return ResourceManager.GetString("StringStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        internal static string TableColumnAddress {
            get {
                return ResourceManager.GetString("TableColumnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string TableColumnContractName {
            get {
                return ResourceManager.GetString("TableColumnContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string TableColumnContractorName {
            get {
                return ResourceManager.GetString("TableColumnContractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Age.
        /// </summary>
        internal static string TableColumnEmployeeAge {
            get {
                return ResourceManager.GetString("TableColumnEmployeeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        internal static string TableColumnEmployeeId {
            get {
                return ResourceManager.GetString("TableColumnEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string TableColumnEmployeeName {
            get {
                return ResourceManager.GetString("TableColumnEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts count.
        /// </summary>
        internal static string TableColumnInvoicesCount {
            get {
                return ResourceManager.GetString("TableColumnInvoicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prepare context.
        /// </summary>
        internal static string TitleContextPreparation {
            get {
                return ResourceManager.GetString("TitleContextPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contractors.
        /// </summary>
        internal static string TitleContractors {
            get {
                return ResourceManager.GetString("TitleContractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contracts.
        /// </summary>
        internal static string TitleContracts {
            get {
                return ResourceManager.GetString("TitleContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customers.
        /// </summary>
        internal static string TitleCustomers {
            get {
                return ResourceManager.GetString("TitleCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Documents.
        /// </summary>
        internal static string TitleDocuments {
            get {
                return ResourceManager.GetString("TitleDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List.
        /// </summary>
        internal static string TitleEmployeeList {
            get {
                return ResourceManager.GetString("TitleEmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        internal static string TitleEmployees {
            get {
                return ResourceManager.GetString("TitleEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quit.
        /// </summary>
        internal static string TitleExit {
            get {
                return ResourceManager.GetString("TitleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill table with fake data.
        /// </summary>
        internal static string TitleFillTableWithFakeData {
            get {
                return ResourceManager.GetString("TitleFillTableWithFakeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Init data.
        /// </summary>
        internal static string TitleInitData {
            get {
                return ResourceManager.GetString("TitleInitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main menu.
        /// </summary>
        internal static string TitleMainMenu {
            get {
                return ResourceManager.GetString("TitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на References.
        /// </summary>
        internal static string TitleReferences {
            get {
                return ResourceManager.GetString("TitleReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translations.
        /// </summary>
        internal static string TitleTranslations {
            get {
                return ResourceManager.GetString("TitleTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string TitleTranslationsDefault {
            get {
                return ResourceManager.GetString("TitleTranslationsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        internal static string TitleTranslationsRuRU {
            get {
                return ResourceManager.GetString("TitleTranslationsRuRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wipe data.
        /// </summary>
        internal static string TitleWipeData {
            get {
                return ResourceManager.GetString("TitleWipeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wipe table data.
        /// </summary>
        internal static string TitleWipeTables {
            get {
                return ResourceManager.GetString("TitleWipeTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not defined.
        /// </summary>
        internal static string ValueAgeIsNotDefined {
            get {
                return ResourceManager.GetString("ValueAgeIsNotDefined", resourceCulture);
            }
        }
    }
}
